### ISSUE TITLE
switch to sublime text 3

### ISSUE THREAD

**Issue by prydonius** [brgmnn/dotfiles#9]
trolololol

**Comment by brgmnn** [comment]
lol thanks

**Comment by chutsu** [comment]
Errr, no Adnan ... vim FTW

**Comment by prydonius** [comment]
You know nothing, @chutsu snow

**Comment by chutsu** [comment]
@prydonius I know that Sublime won't be around in 10 years time :p

**Comment by prydonius** [comment]
@chutsu it's ok I'll switch to Atom
